# Generated by Django 2.1.7 on 2019-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='pic_folder/')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=10)),
                ('conform_password', models.CharField(max_length=10)),
            ],
        ),
    ]
